# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 22f80cb7da19a66a0e2a06bb5020aa04e8bd7ecad0e2dc2b351d52ea7e686504f63f97e4f58ee6290447ecf75b3c66e0d9e5c7b344d3f4e69db966517d493140

test:
  secret_key_base: 9f4b98750aa1ad627aa53f3213dd9791edaba6f74930666e0b653f13e106b9391b2fc0dfb0672c19dbc72180f1160abf444828c1373957637b64cb6e806f37cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
